### ISSUE TITLE
Should have a simple yaml config file.

### ISSUE THREAD

**Issue by rhatdan** [runcom/trust-plugin#2]

**Comment by runcom** [comment]
what do we put in this config file?

**Comment by runcom** [comment]
I'm thinking a switch for `auto-puliing-and-tagging` as per #1 - which may be used in k8s and clusters generally

**Comment by runcom** [comment]
code is in master and conf file under `/etc/docker/trust-plugin.yaml` (like the other plugin conf file under `/etc/docker`)

**Comment by rhatdan** [comment]
All of the comand line switches could be stored in the yaml file, rather then hacking on this via /etc/sysconfig/trust-plugin

**Comment by runcom** [comment]
> All of the comand line switches could be stored in the yaml file, rather then hacking on this via /etc/sysconfig/trust-plugin

right, that's how I did it - there was never a /etc/sysconfig/trust-plugin also - you can now store almost everything under /etc/docker/trust-plugin.yaml

**Comment by rhatdan** [comment]
Awesome, I did not really search the code for this, just read the man page.  Man page should talk about the configuration file if it does not.
